[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psycopg2>=2.9.10",
    "psycopg2-binary>=2.9.10",
    "python-socks>=2.7.1",
    "setuptools>=80.9.0",
]
